name: param_tuner
channels:
  - defaults
dependencies:
  - python=3.7.4
  - pip=20.0.2
  - pip:
    - cookiecutter==1.7.0
    - lightgbm==2.3.1
    - hyperopt==0.2.3
    - mlflow==1.7.2
    - numpy==1.17.0
    - pandas==0.25.0
    - scikit-learn==0.22.2
    - seaborn==0.10.0
    - matplotlib==3.2.1

